
example_1 = 1
secure_build = 1


ifeq ($(example_1),1)
    CFLAGS += -D SPM_EXAMPLE=1
    CFLAGS += -D TFM_EXAMPLE=0
else
    CFLAGS += -D SPM_EXAMPLE=0
    CFLAGS += -D TFM_EXAMPLE=1
endif





# If secure_build is true will it use:
# nrf5340_xxaa_application.ld and gcc_startup_nrf5340_application.s
# If it is false will it use:
# nrf5340_xxaa_application_ns_my.ld and gcc_startup_nrf5340_ns_my.s
# If secure_build is 2 will it use:
# nordic_nrf_bl2.ld and startup_nrf5340_bl2.S

# If example_1 is true will it use:
# SPM configured linker and startup script (which is the original nrf)
# If example_1 is false will it use:
# TF-M configured linker and startup scripts

# TODO perhaps: Create a makefile that builds both builds and
#       call a bash script to srec them togheter.

# Scribbles
# Jump into secure_build and build
# Jump out and into non_secure and build.
# Merge the hex files and flash to embedded system.
